# Server Configuration 
server:
  context-path: /datawarehouse
  port: 8181

# Multipart File configuraiton
spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  h2:
    console:
      enabled:  true
      path: /h2
  datasource:
    url: jdbc:mysql://localhost:3306/warehouseschema?autoReconnect=true&useSSL=false
    username: root
    password: 221255
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate: 
        order_inserts: true
        order_updates:  true
        jdbc.batch_versioned_data : true
        dialect : org.hibernate.dialect.MySQL5Dialect
#        generate_statistics: true
    hibernate:
      ddl-auto : create-drop
 
 # create and drop tables and sequences, loads import.sql 
#spring.jpa.show-sql=true 

# logging   
logging:
  file: /logs/application-debug.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  level:
    root: info
    com.progresssoft: info
    org.springframework. web: info 
    org.hibernate.SQL: info


 